on:
  issues:
    types: [opened, reopened, edited]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  request-more-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var msg = `Hi there :wave:!

            I noticed that this new issue/PR doesn't provide any description, so I labeled it with *needs-more-info*.

            In order for us to be able to review your contribution and answer questions more quickly, please
            describe it in more detail. A thorough description will also help people from the future, who
            are looking for some quick context around this set of changes.

            A great way to start is to follow the <a href="https://github.com/jupyterhub/.github/tree/master/.github/ISSUE_TEMPLATE">issue templates</a> or the repository specific
            PR template (if any). Ultimately, the most important question to answer in your
            description is: *what goal do you want to achieve with this change?*.

            Thank you! :heart:`

            if (context.eventName === 'pull_request') {
              var body = context.payload.pull_request.body
            } else {
              var body = context.payload.issue.body
            }

            // createComment
            if (!body) {
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: msg
                })

                // apply label
                github.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['needs-more-info']
                })
            } else {
              label = github.issues.getLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'needs-more-info'
                })
              if(label) {
                github.issues.deleteLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: 'needs-more-info'
                })  
              }
            }
